### ISSUE TITLE
Armor stands not being cleared up when chest dropped

### ISSUE THREAD

**Issue by TomLewis** [Guarmanda/LootChest#66]
Were on the hunt for bad entitiy farms and one of the issues that appered in our search turned out to be LootChest not cleaning up the armor stand mess its made!

here are 693 armor stands all in the same spot. I have had to run `/minecraft:kill @e[type=armor_stand,distance=..10]` to kill them.

please can you make sure you are removing any entities you are throwing into the world that should be temporary!

![unnamed](https://github.com/Guarmanda/LootChest/assets/144046/0aa09685-cd9c-4e46-af20-ac9c7ca55abb)

![unnamed](https://github.com/Guarmanda/LootChest/assets/144046/5ff5eb5a-a43b-4616-8028-985ee4a88b4d)

**Comment by Guarmanda** [comment]
Lootchest generates armorstands only for fall effect 🤔 maybe I should replace thé fall effect block with packets to not generate entities at all

**Comment by TomLewis** [comment]
sounds like a good idea!

**Comment by Guarmanda** [comment]
Oh, you can also not use armorstands for fall effect, but you'll be limited to some blocks

**Comment by Guarmanda** [comment]
I learnt how to use NMS and created armorstands packets instead of real armorstands. This issue should be gone for next release; this was the last entity spawned by my plugin (fall effect also spawns fireworks, but they aren't problematic).
Packets haves the drawnback to need to be moved manually, I don't know if it'll consume cpu or not, but at least, no more bugged entities

**Comment by TomLewis** [comment]
awesome!

**Comment by Guarmanda** [comment]
Update done, this won't append ever again, armorstands are now packets in ALL versions
