### ISSUE TITLE
Lootchests with random spawning range disabled will drop on players heads with use_players_locations_for_randomspawn set to true

### ISSUE THREAD

**Issue by brandonbunce** [Guarmanda/LootChest#8]
For my server, I have two types of Lootchests in use:

**Monuments:** chests that respawn in **fixed positions** in custom-built "monuments" throughout the world
**Lootdrops:** chests that should spawn **randomly around player locations within 1500 blocks.**

The problem I am having is that the Monument chests, even though their random respawn range is disabled (set to 0) are still using the player locations and dropping the chests on players heads! They should be respecting the random respawn range being set to 0 and respawning where they were made.

**Comment by Guarmanda** [comment]
I'd like to see your data.yml O_o
You can send it with discord, or here, or pastebin, or wherever you want

**Comment by brandonbunce** [comment]
I had to remove all of the monument chests because of aforementioned issues...
But I created a chest called "MonumentTest" which is what the behavior of the monument chests were set to.

[data.txt](https://github.com/Guarmanda/LootChest/files/5539192/data.txt)

**Comment by brandonbunce** [comment]
Any updates on this?

**Comment by Guarmanda** [comment]
Firgetted to check, you did good to ask. So yes, the chest seems do be done correctly. So what you say is really weird, because chests that are using player locations should spawn AROUND players, and not even ON them :/ so I don't understand how it could be possible...Oh gode, I just watched the code and it seems that using player locations for randomspawn makes the plugin using player location for anything... I'll edit the source code right now, but I don't plan to do a new version until a long time

**Comment by Guarmanda** [comment]
this is now fixed
